# Generated by Django 5.0.3 on 2024-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_iamge_url', models.URLField()),
                ('registration_date', models.DateTimeField()),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('expertise', models.CharField(blank=True, max_length=100)),
                ('courses_taught', models.ManyToManyField(related_name='taught', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_iamge_url', models.URLField()),
                ('registration_date', models.DateTimeField()),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('courses_enrolled', models.ManyToManyField(related_name='Enrollment', to='course.course')),
                ('courses_finished', models.ManyToManyField(related_name='Finished', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
