# Generated by Django 5.0.3 on 2024-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_text', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(auto_now=True)),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(max_length=50)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
