# Generated by Django 5.0.3 on 2024-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organizations',
            field=models.ManyToManyField(related_name='organizations', to='organizations.organization'),
        ),
    ]
