# Generated by Django 5.0.3 on 2024-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('org_type', models.CharField(choices=[('U', 'University'), ('C', 'Company')], default='University', max_length=1)),
                ('website', models.URLField()),
                ('logo_url', models.URLField()),
            ],
        ),
    ]
